
version: '3.3'

services:
  data_source_streamlit:
    build: ./

    # command: gunicorn --bind 0.0.0.0:7500 --timeout 5000 app:app
    command: streamlit run app.py
    ports:
      - 8024:8024
 
    hostname: data_source_streamlit
    restart: always
    container_name: data_source_streamlit


 



    
