# pull the official base image
#FROM python:3.8.1-alpine
FROM ubuntu

# set work directory
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

# packages linux---

RUN apt-get update && apt-get -y install python3

RUN apt-get -y install python3-pip

RUN pip3 install --upgrade pip
RUN apt-get update


RUN pip3 install psycopg2-binary

# Libraries or Dependencies --
COPY /requirements.txt /usr/src/app
RUN pip install -r requirements.txt
COPY /. /usr/src/app

EXPOSE 8203
# Run app.py when the container launches

CMD ["--bind", "0.0.0.0:8024", "app:app"]
